### ISSUE TITLE
Input-Dialoge bei Meetingseinstellungen leer lassen crasht App

### ISSUE THREAD

**Issue by jmhoffmann9612** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#39]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 29384
    java.lang.NumberFormatException: For input string: ""
        at java.lang.Long.parseLong(Long.java:606)
        at java.lang.Long.parseLong(Long.java:636)
        at com.example.myapplication.SettingsActivity.lambda$setupListener$0$com-example-myapplication-SettingsActivity(SettingsActivity.java:89)
        at com.example.myapplication.SettingsActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:10)
        at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:346)
        at android.os.Looper.loop(Looper.java:475)
        at android.app.ActivityThread.main(ActivityThread.java:7889)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

**Comment by jmhoffmann9612** [comment]
Behoben in https://github.com/ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent/pull/40.
